### PR TITLE
ApacheVFS 2.0 support

### PR DESCRIPTION
**Pull request by msiuts**
I switched the vfs-s3 implementation to Apache VFS 2.0 which was released in August.

I removed the SNAPSHOT dependency to JetS3t, just because I hadn't the snapshot available in any repository. The multiple-upload-test does fail therefore, but the other tests are just fine (we will have to do something about the big file test too, because there is no iso available).

### CODE REVIEW

**Comment by abashev** [comment]
Moritz, for big file tests you can take any big file (I've just took first iso on my NAS).

But I can't fully accept your request. First of all what the reason why we need VFS 2? Does it add some new functionality or fix some bugs? Also double copy issue is important for me and we need to test current 0.8.1a version for this reason.

**Comment by msiuts** [comment]
VFS 2.0 has native WebDAV support, which is important for me (but not for VFS-S3 Plugin). It also has several bugfixes and FTPS support.

I think it's important to support the latest version of VFS, but maybe it's best to do it on a branch and maybe with another Maven artifact id. Don't you think VFS 2 should support S3 just as VFS 1? So you could pull my changes in a branch.

I also think the double copy issue is very important, but I'm petty sure my branch will work with the latest JetS3t snapshot just as yours. I just hadn't the snapshot artifact in any repo and was too lazy to get it.

**Comment by abashev** [comment]
It make sense. I'll do a merge.

**Comment by abashev** [comment]
Moritz, you did a great job. Thank you!!!

**Pull request merged**
