### PR TITLE
Upgraded aws-java-sdk to 1.8.11

### PR DESCRIPTION
**Pull request by dekobon**
Fixes https://github.com/abashev/vfs-s3/issues/23

### CODE REVIEW

**Comment by dekobon** [comment]
Apparently, I can't figure out how to properly set the S3 key. Or there is a problem with upgrading. I'm going to go see if I can find documentation on how to run the tests.

**Comment by dekobon** [comment]
All tests pass when I enter my S3 credentials into the config.properties file. I suspect that Travis doesn't have a S3 key. I have no idea how to set it for Travis without checking it in.

**Comment by abashev** [comment]
I think travis just don't process secret variable for pull-requests - you could add code for dumping my S3 keys and get it with your pull request. I'll check it

**Comment by dekobon** [comment]
Well if you are OK with the pull request, I'm don't think we need to get Travis working with pull requests.

**Comment by abashev** [comment]
@dekobon I'm really sorry but right now I can't push AWS version to 1.8.11 because we are using a little older version inside our project and we need more testing to change it at newest one. So I did update to 1.8.3 and put your version on testing

**Pull request closed without merging**
