### PR TITLE
Improve reliability of large file uploads

### PR DESCRIPTION
**Pull request by svella**
1. Only use TransferManager for files larger than the multi-part threshold (16MB).
2. Create and destroy TransferManager for each uploaded large file since relative overhead is very small and and some usage patterns are causing the thread pool to get leaked.
3. Always upload from File object since that is the only case where the upload will be retried automatically by the AWS SDK.
4. Allow configuration of maximum number of upload parallel threads since the default of 10 performs very poorly and seems to cause lots of errors, and can saturate network upload bandwidth.

### CODE REVIEW

**Comment by svella** [comment]
Retracting due to merge issues

**Comment by svella** [comment]
Merge issue is that it won't compile without dependency on newer version of AWS SDK which I didn't include because pending pull request #24, which I mistakenly thought had been accepted. Not sure what the best way to proceed would be.

**Comment by abashev** [comment]
I'll update it today.

**Comment by svella** [comment]
Now that SDK version is updated, this should be good to go.

**Pull request merged**
